apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: netology-homework
spec:
  selector:
    name: web
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  - name: multitool
    port: 8080
    protocol: TCP
    targetPort: 8080
